# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194UMXxSLvN19vZW7uYqwkoisDkF55f5U
"""

!pip install dash pandas plotly

# Importação das bibliotecas necessárias
import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html # Changed from JupyterDash to Dash
from google.colab import files

# Lendo o arquivo CSV enviado
file_name = 'ecommerce_estatistica (3).csv'

# Use as linhas a seguir para carregar o arquivo, caso ele não esteja no seu ambiente Colab
# uploaded = files.upload()
# if file_name in uploaded:
#     df = pd.read_csv(file_name)
# else:
#     print(f"Arquivo '{file_name}' não encontrado. Por favor, certifique-se de que ele foi carregado.")
#     exit()

# Para fins de demonstração, assumindo que o arquivo já foi carregado ou está disponível
try:
    df = pd.read_csv(file_name)
except FileNotFoundError:
    print(f"Erro: Arquivo '{file_name}' não encontrado. Por favor, carregue o arquivo.")
    # Você pode descomentar o código de upload de arquivo acima para permitir o upload interativo.
    exit()


# Inspecionando o DataFrame para confirmar as colunas e tipos de dados
print("Primeiras 5 linhas do DataFrame:")
print(df.head())
print("\nInformações sobre as colunas do DataFrame:")
df.info()

# Preenchendo valores nulos na coluna 'Gênero' para evitar erros no agrupamento
df['Gênero'] = df['Gênero'].fillna('Não especificado')

# Convertendo a coluna 'Qtd_Vendidos' para numérico, tratando erros
df['Qtd_Vendidos'] = pd.to_numeric(df['Qtd_Vendidos'], errors='coerce').fillna(0)

# Criando um gráfico de barras com a quantidade de itens vendidos por gênero
# Agrupando os dados e somando a quantidade vendida
df_agg = df.groupby('Gênero')['Qtd_Vendidos'].sum().reset_index()

# Criando o gráfico usando Plotly Express
fig = px.bar(
    df_agg,
    x='Gênero',
    y='Qtd_Vendidos',
    title='Total de Itens Vendidos por Gênero',
    labels={'Gênero': 'Gênero do Produto', 'Qtd_Vendidos': 'Quantidade Total Vendida'},
)

# Criando o aplicativo Dash
app = Dash(__name__) # Changed from JupyterDash to Dash

# Definindo o layout do aplicativo
app.layout = html.Div(children=[
    html.H1(
        children='Dashboard de Estatísticas de E-commerce',
        style={'textAlign': 'center', 'color': '#7FDBFF'}
    ),

    html.Div(
        children='Análise de vendas baseada no gênero dos produtos.',
        style={'textAlign': 'center', 'color': '#7FDBFF'}
    ),

    dcc.Graph(
        id='grafico-vendas-genero',
        figure=fig
    )
])

# Executando o servidor do Dash. No Google Colab, o Dash agora funciona de forma nativa
if __name__ == '__main__':
    app.run(debug=True) # Changed from app.run_server to app.run